### ISSUE TITLE
Cannot set initial value for only one window

### ISSUE THREAD

**Issue by SukantPal** [palantir/react-mosaic#105]
### Bug report

Package version(s):  ^2.1.0
Browser and OS versions: Firefox and Chrome, on Ubuntu Linux 18.04

#### Steps to reproduce

1. Create a new application component and try to initialize it for react-mosaic

2. Use this code in it:

       renderTile(id, path) {
           return (
                <MosaicWindow path={path} title={ "Media Display" }>
                     <h1 style={{color:'black'}}>Window + { "Media Display"}</h1>
                </MosaicWindow>
           );
        }

        render() {
            return (
                <div id="studioApp" style={{width:'100%', height:'100%'}}>
                    <Mosaic createNode={ () => {return MEDIA_DISPLAY_WIN;}}
                       renderTile={ this.renderTile.bind(this) }
                       initialValue={{ direction: 'row', first: 'your-window-any', second: null}}/>
                </div>
             );
        }

So our initial value has only one window: `your-window-any` id. Suppose I don't want the second window: I would leave out `second` - making it undefined, or I would define it null - as shown here. Your `renderRecursively` method crashes due to not being able 

#### Actual behavior

`renderRecursively` in mosaic crashes as `node is undefined` or `node.direction` couldn't be read (null or undefined value of `second` in `initialValue`).

#### Expected behavior

Only one window should be shown.

**So far, I haven't found a workaround. This is a major documentation problem indeed.**

**Comment by nomcopter** [comment]
A tile cannot be null or undefined. The following does what you want:
`<Mosaic createNode={ () => {return MEDIA_DISPLAY_WIN;}}
                renderTile={ this.renderTile.bind(this) }
                initialValue="your-window-any" />`

**Comment by SukantPal** [comment]
Okay, thanks. I think it should be cleared in the README.md file of this project.
