### ISSUE TITLE
Nested layouts and drag&drop

### ISSUE THREAD

**Issue by the-spyke** [palantir/react-mosaic#13]
Is there a way to render several Mosaic layouts side by side and prevent drag&drop from one layout to another? What about nested layouts? I can render it, but drag&drop allows me to drop tile on another layout, which make no sense and doesn't work.

**Comment by nomcopter** [comment]
It is currently not possible. What is your use case for wanting multiple side-by-side or having nested Mosaics? Using one Mosaic should support arbitrary nesting.

**Comment by the-spyke** [comment]
I have a basic layout on Mosaic. Something like a dashboard. Client can create custom widgets to render in a dashboard's tile. One of such widgets has it's own layout and it's very convenient to make it with Mosaic too.

**Comment by nomcopter** [comment]
Cool - fixed. Would love a screenshot of your use case :)

**Comment by the-spyke** [comment]
Wow, thank you. I will try it tomorrow with modified ExampleApp.

Unfortunately, I have no actual screenshot. We want to use something more tile-based than `react-grid-layout`. So, I've started to investigate existing libraries and found `react-mosaic`. ExampleApp was promising, but we need nesting. Right now we have only one widget with nested layout: a table with a bunch of sidebars and menus. You can configure, where on which side those sidebars/menus will be and resize all this. But more widgets with such layout are coming.
