### ISSUE TITLE
ViewId cannot be zero

### ISSUE THREAD

**Issue by andrew8088** [palantir/react-mosaic#15]
I have an array of window definitions, and set the viewId to be the index of the definition in the array. For example:

```
const layout = {
  direction: 'row',
  first: 0,
  second: {
    direction: 'column',
    first: 1,
    second: 2
  }
};
```

However, when I drag the first window, I get this error:

```
Path [first] did not resolve to a node
```

It's because in the `getNodeAtPath` function, the return statement is this:

```
return _.get(tree, path) || null;
```

And since `0 || null` returns `null`, I get the error.

Not sure if supporting 0 (and other falsey values) as a viewId is something you want to do, but I figured I'd ask if this was intentional or not. Thanks for a great library!

**Comment by nomcopter** [comment]
Not intentional. Good catch!
