### ISSUE TITLE
Customizing Mosaic-Window

### ISSUE THREAD

**Issue by bradennapier** [palantir/react-mosaic#18]
Hey there!  So you have a few things hard coded into the mosaic window which I think would be nice to be optionally customizable.  

It would be nice to be able to provide a custom component to render for the preview here.  Likely replacing the entire contents below?

```js
            connectDragPreview(
                div({ className: 'mosaic-preview' },
                    div({ className: 'mosaic-window-toolbar' },
                        div({ className: 'mosaic-window-title' }, title)),
                    div({ className: 'mosaic-window-body' },
                        h4({}, title),
                        span({ className: 'pt-icon pt-icon-application' }),
                    ),
                ),
            ),
```

There are a few others which I will edit when I get to them again.  My main issue here is that I'd like to not rely on the blueprint as I have my own icons that we build in-house.  It's simple enough to trick it but overall I think it would be beneficial to make it easier to switch out to another without re-writing some of the amazing work you have already done on things like this!

Awesome component, by the way!  Thanks a ton!  This has really improved our app over the other component we were using.

**Comment by nomcopter** [comment]
Cool - I'll add the ability to customize the preview. 

As for custom icons - have you looked into overriding the `toolbarControls` in `MosaicWindow`? That should be enough to give you everything you need. Each of the buttons themselves are very simple (See https://github.com/palantir/react-mosaic/blob/master/src/window/defaultToolbarControls.ts)

And thanks! Great to hear.

**Comment by bradennapier** [comment]
Yes those are simple enough to customize -- however the window is hard coded there so I would need to provide it as a css class (I use inline SVG Components generally).  Not sure if icons are used anywhere else but that was the main part i was looking at.

Thanks a ton!
