### ISSUE TITLE
onChange not giving me the right dashboard?

### ISSUE THREAD

**Issue by bradennapier** [palantir/react-mosaic#19]
Not sure if I am doing something wrong here, but I seem to be getting a weird error happening here.  I am using this as a Controlled Component.  I send it the grid and all is well.  However when I am dragging stuff around, the "onChange" handler is giving me the wrong information. 

For example, if I drag and set things so that "foo" is on top and "bar" is on bottom, it is sending me 

```js
{
    direction: 'column',
    first: 'bar',
    second: 'foo',
    splitPercentage: 100
}
```

**Comment by nomcopter** [comment]
This is intentional. Mosaic hides a window as you drag it by setting its sibling to take up the entire pane. This calls onChange to update the rendered value. 
Once a user drops the window in the desired location, onChange should be fired again with the new state. 
Is this causing problems for you?

**Comment by bradennapier** [comment]
Interesting, upon further evaluation - what it actually appears to be doing is rendering the new id but using the old components.  So it sends the new id but the component is always the same.  This probably makes sense but might be good to document this behavior.  

Essentially I have something like this:

```js
const MosaicGrid = ({ children, onChange, wrapperClass, grid, widgets, ...props }) => (
  <Mosaic
    initialValue={grid}
    onChange={onChange}
    renderTile={ id => {
      const widget = widgets[id]
      const title  = widget && widget.title || 'Unknown Widget'
      return (
        <MosaicWindow
          // createNode={ () => 'new' }
          title={ title }
          // toolbarControls={[]}
          additionalControlButtonText='Options'
          additionalControls={[
            <div key='hi'>hi</div>
          ]}
        >
          <RenderWrapper widget={widget} wrapperClass={wrapperClass} />
        </MosaicWindow>
      )
    } }
  />
);
```
So RenderWrapper receives the new widget but it doesn't re-render.

**Comment by nomcopter** [comment]
This problem doesn't sound specific to react-mosaic, React will attempt to reuse existing elements on rerender based on their location in the DOM. Nearly any time you have logic in componentWillMount you also want it in componentWillRecieveProps.

**Comment by bradennapier** [comment]
Ok so that worked great.  I did it that way because originally it was unmounting then remounting every single component and I wasn't sure if that was behavior that react-mosaic was doing itself but now I see where that behavior came from.  

My next concern which is untested is the behavior that occurs while dragging.  I am automatically persisting the grid locations on a throttle.  So basically I receive and update locally the grid that I receive within the local state of the parent.  After a second of no new changes, I then persist the state so that the grid will always stay up-to-date for that user.  

While likely rare, my concern is that since I receive this:

```js
{
   direction: 'row'
    first: 'foo',
    second: 'bar',
    splitPercentage: 0
}
```
If the site crashes before a drop or any other force quit where the operation could not be completed it could cause issues.

Easy enough fix - don't save when splitPercentage is 0. However it leads me to wonder if it might be a good idea to include (perhaps in another argument) a value to let us know that a drag is occurring and/or what is being dragged?  Just an idea!

Anyway - working awesome now!  Truly appreciate it!

![image](https://cloud.githubusercontent.com/assets/15365418/25687116/7bb6c94a-3028-11e7-9c1c-f8b40b0289f5.png)

**Comment by nomcopter** [comment]
Yeah the continuous unmount/remounting is unfortunate and tracked here https://github.com/palantir/react-mosaic/issues/2. 
React 16.x looks like it may add something for us to work with though 🤞
