### ISSUE TITLE
Text Selection when dragging

### ISSUE THREAD

**Issue by andrew8088** [palantir/react-mosaic#20]
I'm having an issue with text selection inside the windows when a user tries to adjust the layout. It happens often when resizing windows, and sometimes when moving windows as well. A little research seems to suggest that calling `evt.preventDefault` on the `mousedown` and `mousemove` events would solve this.

Is this something react-mosaic could do? Or is there a better way that I could handle this myself? Thanks!

**Comment by nomcopter** [comment]
Good call - fixed the text selection from window resize. 
I couldn't reproduce it when dragging windows however. If you are still running into problems - this is fairly easy to handle in CSS using `user-select: none`, as done in the example app here: https://github.com/palantir/react-mosaic/blob/master/dev/example.less#L46

**Comment by andrew8088** [comment]
Thanks so much!
