### ISSUE TITLE
Using "MosaicWindow" uses 400MB + GPU

### ISSUE THREAD

**Issue by bradennapier** [palantir/react-mosaic#21]
So not really sure what is specifically happening here but I have now narrowed my performance issues after an insane amount of hours spent confused.  Whenever I render using MosaicWindow my app is using about 500 MB of GPU to render.  Therefore my FPS is about 2-3 rather than 60 which is what I am at with the previous version rendering the same content and data.

If i render mosaic without the MosaicWindow my app uses 100 MB (2 tiles total).  If i use MosaicWindow it hits about 480 and any slight change (for example dragging a google map around) puts it up to the max and my fan runs like crazy and my FPS is < 5. 

Once I discovered this was the issue I found some pretty odd results.

I discovered the rule at `.mosaic-root.mosaic-blueprint-theme .mosaic-window, .mosaic-root.mosaic-blueprint-theme .mosaic-preview`

This has a border-radius of 3px.  That css rule alone is costing 150 MB of GPU for me?

It obviously makes a big difference the size of the screen here for the sake of simplicity this shows with dev tools attached rather than detached on a different monitor like it was during my initial testing:

![image](https://cloud.githubusercontent.com/assets/15365418/25777521/7b572152-3294-11e7-9a7c-2f46dbc1eb64.png)

Disabling that single CSS Rule puts me up to 60 FPS:

![image](https://cloud.githubusercontent.com/assets/15365418/25777527/8d273264-3294-11e7-8127-c153dc40fa7e.png)

This appears to be something related to chrome rendering border-radius poorly. [reference](http://stackoverflow.com/questions/20001515/chrome-bug-border-radius-not-clipping-contents-when-combined-with-css-transiti)

As when I add `z-index: 0` to that rule it brings it down 70 MB (but still uses 40MB)

I also get the same effect as z-index: 0 when I use transform to get that layer rendered with hardware acceleration

![image](https://cloud.githubusercontent.com/assets/15365418/25777550/3c8da7e2-3295-11e7-93b6-af8717e4805e.png)

Upon continued experimentation by removing anything with these types of css rules I got the memory down big time - although still a bit higher than I would expect (about 70-80 would be expected with the large map):

![image](https://cloud.githubusercontent.com/assets/15365418/25777627/b12cb3e8-3297-11e7-90ab-7a5fde802016.png)

I am sure this is some odd rendering bug as it seems to have started as soon as  I upgraded to the newest version of chrome.  It could also be some conflicting rule somewhere that doesn't like to merge with my own -- not sure... but either way wanted to point it out.

**Comment by bradennapier** [comment]
I would also point out it appears that it may have to do with the Retina screen that OSX provides as this problem would only occur on my OSX Monitor -- using my external monitor did not produce the problem - although obviously the resolution is significantly less there.

**Comment by nomcopter** [comment]
Wow. That's super weird.
Closing this for now as you've found a workaround and this looks like a Chrome rendering bug. Thanks for the useful debugging info!
