### ISSUE TITLE
lift minimum percentage being 20?

### ISSUE THREAD

**Issue by ZachLiuGIS** [palantir/react-mosaic#22]
Hi, We are exploring incorporating react-mosaic into our project, but our layout needs some narrow tiles, can minimum percentage be lifted? You can create narrow tiles in initial values, but as soon as you resize, it will go to 20 by default.

**Comment by SukantPal** [comment]
Why was this closed without any resolvation?

**Comment by nomcopter** [comment]
It was closed by implementing it. Check `ResizeOptions`
