### ISSUE TITLE
Store layout

### ISSUE THREAD

**Issue by 2silver** [palantir/react-mosaic#23]
It would be nice, if the current layout will be stored - and reopened after page reload

By the way, Great product  👍

**Comment by nomcopter** [comment]
This behavior is quite easy to implement using the provided callbacks. For example:

```tsx
<Mosaic
  initialValue={localStorage.getItem(LOCAL_STORAGE_KEY) || DEFAULT_VALUE}
  onChange={(node) => localStorage.setItem(LOCAL_STORAGE_KEY, node)}
  ....
/>
```

`localStorage` here can be replaced with whatever implementation of session storage you desire.

And thanks!
