### ISSUE TITLE
CSS 

### ISSUE THREAD

**Issue by bradennapier** [palantir/react-mosaic#24]
The blueprint css is pretty massive.  Would be a nice goal -- although not a true "issue" - to make this no longer dependent on blueprint to save the 300-400kb that the base package takes up.  

I have customized it completely at this point but I did so by just editing the blueprint css -- there is so much there that it is nearly impossible to figure out what is and is not needed.  

I do want to take another moment to say thank you.  No other package has contributed as much to the user experience as this one.

Err just saw the .less file you added - if that is all that is needed then I think for the most part you already took care of this :-P

**Comment by nomcopter** [comment]
As you discovered, it does not depend on blueprint if you remove the mosaic-blueprint-theme class.

**Comment by nomcopter** [comment]
And thanks! Glad it works well for you.
