### ISSUE TITLE
Disable resize for a single window

### ISSUE THREAD

**Issue by Leandro-Andrade** [palantir/react-mosaic#25]
Hey guys!
Is there a way out of the box where I can make a specific window with `resize = "DISABLED"`?
I could only make all fixed or none.

![capture](https://cloud.githubusercontent.com/assets/7105050/26826700/5c633f60-4a90-11e7-8cb1-0fc559451616.PNG)

I need to make them all resizable, **except Window 11**, so if I resize window 10 to the right, window 11 will continue with the same width and **only** window 12 will be more narrow.

Would any one please help me to achieve this?

Thank you in advance!

**Comment by nomcopter** [comment]
This logic should be possible to implement in the `onChange` handler. For example, something like:

```tsx
<Mosaic
  value={this.state.node}
  onChange={(node) => {
    if (hasChangedWindow11(node)) {
      this.setState({ node: preserveWindow11(node) });
    } else {
      this.setState({ node });
    }
  }}
  ....
/>
```
