### ISSUE TITLE
Moving to react-dom-factories?

### ISSUE THREAD

**Issue by andrew8088** [palantir/react-mosaic#32]
When using react-mosaic with React 15.6.1, you get the following warning:

> Warning: Accessing factories like React.DOM.div has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories

react-mosaic is using React's DOM factories in the following places; just wondering if there are plans to prepare react-mosaic for React 16?

https://github.com/palantir/react-mosaic/blob/785638b21294440ce42990c0ff41b0895785c80d/src/Mosaic.ts#L31

https://github.com/palantir/react-mosaic/blob/785638b21294440ce42990c0ff41b0895785c80d/src/MosaicZeroState.ts#L22

https://github.com/palantir/react-mosaic/blob/785638b21294440ce42990c0ff41b0895785c80d/src/MosaicDropTarget.ts#L25

https://github.com/palantir/react-mosaic/blob/785638b21294440ce42990c0ff41b0895785c80d/dev/ExampleApp.ts#L38

https://github.com/palantir/react-mosaic/blob/785638b21294440ce42990c0ff41b0895785c80d/src/MosaicTile.ts#L24

https://github.com/palantir/react-mosaic/blob/785638b21294440ce42990c0ff41b0895785c80d/src/window/defaultToolbarControls.ts#L22

https://github.com/palantir/react-mosaic/blob/b3c78717f364743bb844c41e605c9d5999c3ddd5/src/window/MosaicWindow.ts#L34

**Comment by nomcopter** [comment]
Yup! I haven't had the time to do it recently, but it's on the list. Accepting PRs as well :)

**Comment by bradennapier** [comment]
React 16 RC is out.  This whole package will stop working shortly :(

**Comment by bradennapier** [comment]
React 16 official reelease is today so all apps using this package can not upgrade officially.  Created a shitty pull request - it shouldnt take more than 10 minutes if you know TS to simply change all the imports here

**Comment by nomcopter** [comment]
Cool, will bundle this with a couple other fixes today!
