### ISSUE TITLE
Error thrown when dropping window immediately on itself.  (RENAMED FROM: Immediately dropping window on its own header sometimes causes the window to disappear.)

### ISSUE THREAD

**Issue by aldensc** [palantir/react-mosaic#33]
Possible fix (SCA) in MosaicWindow.js (line 56) ...

    endDrag: function (_props, monitor, _a) {
        var context = _a.context;
        var path = context.getMosaicPath();
        var dropResult = (monitor.getDropResult() || {});
        var position = dropResult.position, destinationPath = dropResult.path;

        // SCA: Fixed destinationPath check.  Did not handle the case where the destination was undefined or where it was the same as the source path.
        //      New logic and old logic combined into a new invalidDestinationPath variable.
        //      These situations could be created when dropping the window as soon as it started to be dragged (I.E. within the same window or header).
        var invalidDestinationPath = destinationPath == undefined && destinationPath == null || destinationPath.length == 0 || ((path.length == destinationPath.length) && path.every(function (element, index) {
            return element === destinationPath[index];
        }));

        if (position != null && !invalidDestinationPath) {
            context.mosaicActions.updateTree(mosaicUpdates_1.createDragToUpdates(context.mosaicActions.getRoot(), path, destinationPath, position));
        }
...

**Comment by nomcopter** [comment]
What browser? I can't repro this.

**Comment by aldensc** [comment]
Tried with IE 11.0.9600.18738 and Chrome 60.0.3112.113.  Both with the same results.  My "fix" did not actually fix it.  It stops an error from being thrown.  My fix hides the error, but causes the window to disappear.  
<img width="903" alt="screen shot 2017-08-28 at 9 24 59 am" src="https://user-images.githubusercontent.com/7165617/29775428-1cce3826-8bd3-11e7-912b-718590cb26d0.png">
[package.json.txt](https://github.com/palantir/react-mosaic/files/1256873/package.json.txt)


I've uninstalled react-mosaic-component and reinstalled, but did not change the results.  Attaching my package.json and a screenshot of the error.

**Comment by aldensc** [comment]
Attaching one more screenshot.  Walked back the callstack to the createRemoveUpdate so you can see the parameters that is was called with.
<img width="1168" alt="screen shot 2017-08-28 at 9 32 03 am" src="https://user-images.githubusercontent.com/7165617/29775677-111af004-8bd4-11e7-96dc-d1c3fc02f43a.png">

**Comment by aldensc** [comment]
Following the callstack back one step further is the following code...

function createDragToUpdates(root, sourcePath, destinationPath, position) {
    var destinationNode = mosaicUtilities_1.getAndAssertNodeAtPathExists(root, destinationPath);
    var updates = [];
    var destinationIsParentOfSource = isPathPrefixEqual(sourcePath, destinationPath, destinationPath.length);
    if (destinationIsParentOfSource) {
        // Must explicitly remove source from the destination node
        destinationNode = updateTree(destinationNode, [
            createRemoveUpdate(destinationNode, _.drop(sourcePath, destinationPath.length)),
        ]);
    }

destinationIsParentOfSource is evaluating to true, but it is the same window as the source and not a child of.  I don't think it should fall into the createRemoveUpdate() logic.

**Comment by aldensc** [comment]
Here is what I changed to make this work..
Console messages were to verify the defer requirement of the restore of the hidden window.

 In MosaicUpdates.js...(See SCA: comments)
function createDragToUpdates(root, sourcePath, destinationPath, position) {
  ...
    if (destinationIsParentOfSource) {
        // SCA: source and destination are same, so nothing to update
        if (sourcePath.length == destinationPath.length)
            return updates; // dropped on self
       ...
    }

In MosaicWindow.js... (See SCA: comments)
    beginDrag: function (_props, _monitor, _a) {
        var context = _a.context;
        // SCA: using exact path for the restore that was used here in the hide.
        hidePath = context.getMosaicPath();
        // The defer is necessary as the element must be present on start for HTML DnD to not cry
        _.defer(function () {
            console.log("HIDING");
            return context.mosaicActions.hide(context.getMosaicPath());
        });
        return {
            mosaicId: context.mosaicId,
        };
    },
    endDrag: function (_props, monitor, _a) {
        var context = _a.context;
        var path = context.getMosaicPath();
        var dropResult = (monitor.getDropResult() || {});
        var position = dropResult.position, destinationPath = dropResult.path;
        if (position != null && destinationPath != null) {
            var updates = mosaicUpdates_1.createDragToUpdates(context.mosaicActions.getRoot(), path, destinationPath, position);
            if (updates.length > 0) {
                context.mosaicActions.updateTree(updates);
            }
            // SCA: added if/else condition so the restore of the original hide could be done.  Had to defer this, because the hide was deferred.
            //      Otherwise, the hide was happening after the restore.
            else {
                console.log("RESTORE DEFERRED");
                _.defer(function () {
                    var targetPath = _.dropRight(hidePath);
                    console.log("RESTORING");
                    return context.mosaicActions.updateTree([{
                        path: targetPath,
                        spec: {
                            splitPercentage: {
                                $set: null,
                            },
                        },
                    }]);
                });
            }
        }
        else {
            context.mosaicActions.updateTree([{
                    path: _.dropRight(path),
                    spec: {
                        splitPercentage: {
                            $set: null,
                        },
                    },
                }]);
        }
    },

**Comment by aldensc** [comment]
@nomcopter Are you able to see the 'branch undefined' error in the browser?

**Comment by nomcopter** [comment]
Not in Chrome, should be able to test in IE soon.

**Comment by nomcopter** [comment]
Cool got a repro in IE. Should have time to fix soon.

**Comment by aldensc** [comment]
@nomcopter  - Awesome!  I did post my local fix, but not sure that is what you want to do to apply a patch.  If you wish for me to test your fix, let me know.  Thanks!

**Comment by nomcopter** [comment]
Should be fixed now, please verify!

**Comment by aldensc** [comment]
@nomcopter...The error is not happening, but the window is still sometimes hidden when dropped on self.  Looking at the code below... the beginDrag defers the hiding of the window.  In the case where the paths are the same, the endDrag needs to defer the UpdateTree as well.  In my case (maybe a slow Windows VM), the hiding of the window is happening after the endDrag's UpdateTree and the window disappears.  Regards, Scott

const dragSource = {
  beginDrag: (_props: Props<any>, _monitor: DragSourceMonitor, { context }: InternalMosaicWindow<any>): MosaicDragItem => {
    // The defer is necessary as the element must be present on start for HTML DnD to not cry
    _.defer(() => context.mosaicActions.hide(context.getMosaicPath()));
    return {
      mosaicId: context.mosaicId,
    };
  },
  endDrag: (_props: Props<any>, monitor: DragSourceMonitor, { context }: InternalMosaicWindow<any>) => {
    const ownPath = context.getMosaicPath();
    const dropResult: MosaicDropData = (monitor.getDropResult() || {}) as MosaicDropData;
    const { position, path: destinationPath } = dropResult;
    if (position != null && destinationPath != null && !_.isEqual(destinationPath, ownPath)) {
      context.mosaicActions.updateTree(
        createDragToUpdates(context.mosaicActions.getRoot(), ownPath, destinationPath, position));
    } else {
      context.mosaicActions.updateTree([{
        path: _.dropRight(ownPath),
        spec: {
          splitPercentage: {
            $set: null,
          },
        },
      }]);
    }
  },
};

**Comment by nomcopter** [comment]
Heh, that explains why I can't repro most of these weird timing issues. Will look in to.
