### ISSUE TITLE
How to default size change

### ISSUE THREAD

**Issue by YangHeeKyung** [palantir/react-mosaic#34]
![default](https://user-images.githubusercontent.com/22276490/30256934-36896940-96e9-11e7-9294-41dd5959ceee.png)

Good morning

I want to create a layout like the one shown above.
But there are two problems, so I post this article.

1. i want third children 

`` js
initialValue={{
direction: 'column',
first: 'a',
second: 'b'
// i want third 
        }}
``

2.  i want change default size

![2](https://user-images.githubusercontent.com/22276490/30256951-4a236348-96e9-11e7-9cad-99916dd5a40d.png)

how to default size change ?

**Comment by nomcopter** [comment]
Setting `initialValue` to the following results in the view you desire:

```js
{
  "first": 1,
  "second": {
    "direction": "row",
    "first": 2,
    "second": {
      "first": {
        "first": 3,
        "second": 4,
        "direction": "column",
        "splitPercentage": 25
      },
      "second": 5,
      "direction": "row"
    },
    "splitPercentage": 35
  },
  "direction": "column",
  "splitPercentage": 30
}
```

**Comment by YangHeeKyung** [comment]
thank you!
