### ISSUE TITLE
"Additional Controls" API

### ISSUE THREAD

**Issue by bradennapier** [palantir/react-mosaic#36]
I am running into a situation that appears like it will be fairly hacky to do properly.  (Love this package by th eway, it is the core of a lot of our functionality at this point).

So I render some "widgets" with additional options in the given dropdown:

![image](https://user-images.githubusercontent.com/15365418/30836732-e2e7eb5e-a214-11e7-83d3-629297dfa3a4.png)

When the user selects an item from the dropdown, I want the additional controls to close automatically.  Researching how I would have to do this, it would appear the only way would be to get a ref for the MosaicWindow then do something like:

```js
this.windowRef.decoratedComponentInstance.decoratedComponentInstance.setState({ additionalControlsOpen: false })
```

This does appear to work fine, but it is extremely hacky and of course probably prone to breakage on future updates being that it is calling such a deeply nested structure within the component.  Not to mention the ref is in a place that is likely hard to get to -- meaning that you have to move up to something like redux to globally monitor the expected state and control it all which makes it a complete mess!

I would propose that instead, it would make sense to pass some actions down through props to control the state of the window.  This would be fairly simple to accomplish I would think and it would simplify needs such as this.

---

Here is pretty much what I end up doing.  I just keep thinking of all the possible places this could break and it scarin me :-P -- perhaps at the minimum a fn in the top level to set this safely?

```js
// Within the top level component:

  // we store a ref to each MosaicWindow so that we can access the 
  // connected components and control things like the additional 
  // controls visibility.
  windows: {
    [id: string]: any,
  } = {};

  handleCloseAdditionalControls = id => {
    const controls = _.get(
      this.windows,
      `${id}.decoratedComponentInstance.decoratedComponentInstance`,
    );
    if (controls) {
      controls.setState({
        additionalControlsOpen: false,
      });
    }
  };
```

```js

// creating the mosaicWindowProps, excuse the indenting 

const toolbarControls = [];

          if (widget.expandable !== false) {
            toolbarControls.push(
              <div data-tip="Expand" key="expand">
                <ExpandButton onClick={() => dashboard.onWidgetExpandedByUser(widget)} />
              </div>,
            );
          }

          if (widget.removable === true) {
            toolbarControls.push(
              <div data-tip="Remove" key="remove">
                <RemoveButton
                  onClick={() => {
                    dashboard.onWidgetRemovedByUser(widget);
                    Tooltip.hide();
                  }}
                />
              </div>,
            );
          }

const mosaicWindowProps = {
            ref: ref => {
              this.windows[id] = ref;
            },
            title,
            toolbarControls,
            additionalControlButtonText: widget.optionsLabel,
            additionalControls:
              OptionsComponent !== undefined
                ? [
                  <OptionsComponent
                    key={id}
                    widget={widget}
                    dashboard={dashboard}
                    onCloseAdditionalControls={() => this.handleCloseAdditionalControls(id)}
                  />,
                  ]
                : null,
          };
```

---

So if we do not want to do a props injection here, perhaps it would be simpler and more intuitive to just provide something so we can do the following:

```js
handleCloseAdditionalControls = id => {
    const win = this.windows[id]
    if (win) {
      win.setAdditionalControlsState(false)
    }
  };
```

Can probably just be available whether or not additional controls are present and set the state if it does have them and if everything else checks out.

**Comment by nomcopter** [comment]
Added the functionality into `mosaicWindowActions` on `context`. Let me know if that works for you!
