### ISSUE TITLE
What would cause "cannot call hover after drop"

### ISSUE THREAD

**Issue by bradennapier** [palantir/react-mosaic#39]
I am suddenly running into this where I get thousands of errors when I drag/drop windows:

![image](https://user-images.githubusercontent.com/15365418/30996856-af33ddb6-a478-11e7-9af1-49b1d459f05d.png)

The error dont always show - other times I get nothing - the whole app jsut locks up completely when I try to drag/drop things.

It is probably something I am doing wrong - just not wsure where to look.

**Comment by nomcopter** [comment]
Hmm, what version of react-mosaic, browser and OS? My guess is you are throwing an error in a React lifecycle method or in your `onChange`.

I don't think that graph shows a memory leak (or at least not a bad enough one to cause a performance hit). It only increases by 3%.

**Comment by bradennapier** [comment]
Latest of react-mosaic, electron 1.7.8 so Chrome 58 and OSX.  It doesnt happen in production, only in development.... but it happens a lot in development.

React v16 so an error in the lifecycle method should show now within my didCatch

**Comment by bradennapier** [comment]
I am wondering if this has to do with components getting confused / doing extra work when being dragged around.  

Is there a way to know that a drag is occurring so that components can be put into a hibernating state ?

**Comment by nomcopter** [comment]
When a component is dragged around it will be unmounted and a new component with the same props will be remounted because of #2. This means any internal state will be lost. `componentWillUnmount` is the right place to put any cleanup logic.

I can't repro this in the example app or my usages. If you can get me a jsfiddle with a repro or link me to the project you are having problems in I'd be happy to help debug.

Sidenote: What do you use for the `T` in Mosaic? A fix I've been thinking about for #2 restricts it to `string`s and `number`s.

**Comment by bradennapier** [comment]
I think I actually have cut it down to figuring out it happens specifically if I drag the FIRST value.  Happens in production this way as well.  Works fine if I always use the "SECOND" property .. Still debugging. 

If `T` is the ID then I use a string.

**Comment by bradennapier** [comment]
https://www.dropbox.com/s/x5u75h5g7pze6an/Mosaic.mp4?dl=0

**Comment by nomcopter** [comment]
That's super weird. Especially the ridiculous perf. I can't really help without a local repro though :o

**Comment by bradennapier** [comment]
@nomcopter yeah I am trying to figure out the best way to do that.  It is absolutely something weird with the specific way it is rendered.  I use this in a ton of places on the app and this is the place giving major problems.  I cant identify anything different here.

Works flawless in all these other situations (which are actually probably more complex overall).

![image](https://user-images.githubusercontent.com/15365418/31039776-7bddc306-a535-11e7-9aee-342471f7cf0e.png)

![image](https://user-images.githubusercontent.com/15365418/31039796-9b231e3c-a535-11e7-837a-47701cb4a530.png)

**Comment by nomcopter** [comment]
Instinct tells me that an error is getting thrown and swallowed in your `onGridChange` logic or perhaps in `render`. But that's odd that your ErrorGateway isn't catching them. Love the screenshots! Always great to see what people have built using mosaic :)

**Comment by nomcopter** [comment]
Any luck tracking this down?
