### ISSUE TITLE
Component internal state is lost when tree is modified

### ISSUE THREAD

**Issue by brianc** [palantir/react-mosaic#45]
### Bug report

- __Package version(s)__: 0.4.6
- __Browser and OS versions__: chrome & osx

#### Steps to reproduce

1. Create a new layout with a single pane
2. Split the pane with the 'split' button

#### Actual behavior

The original pane is unmounted & two new panes are mounted

#### Expected behavior

The original pane does not unmount, only 1 new pane is mounted.

I'm probably doing something wrong but whenever I split or drag & drop panes around in the layout all of the existing panes are unmounted & a new copy is created and remounted whenever the tree modification is finished.  This is problematic because some of my panes contain components with local state. Their local state is lost when they are unmounted and remounted.  Is there something I could do differently or some way to preserve mounted components which are moved in the tree?

**Comment by nomcopter** [comment]
Caused by #2 

The best workaround for the time being is to hoist your internal state out of the component (into something like Redux).

However, I am working on a fix for #2 that should be in within a week.

**Comment by brianc** [comment]
awesome @nomcopter looking forward to it!  Sorry - i searched the issues but somehow I missed that existing one.  I'll close this & keep my eye on #2.

**Comment by nomcopter** [comment]
I just renamed that one to be more useful, not your bad! :)

**Comment by nomcopter** [comment]
Fixed in v1.0

**Comment by brianc** [comment]
Thanks for the fix! Working perfectly now! 💃  💃
