### ISSUE TITLE
Overlapping tile

### ISSUE THREAD

**Issue by luisbelloch** [palantir/react-mosaic#57]
Hi, 

following the sample from the main readme file, we found that there's a case where tiles overlap after dragging them. We're using default theme. 

![mosaic](https://user-images.githubusercontent.com/160260/35808377-e1689362-0a85-11e8-8790-448f27329da8.gif)

This is the code we're using:

```
import * as React from 'react';
import { Mosaic, MosaicWindow, MosaicNode } from 'react-mosaic-component';

import './deck.scss';

export type ViewId = 'datalist' | 'form' | 'new';

class ViewIdMosaic extends Mosaic<ViewId> {}
class ViewIdMosaicWindow extends MosaicWindow<ViewId> {}

const initial: MosaicNode<ViewId> = {
  direction: 'row',
  first: 'datalist',
  second: {
    direction: 'column',
    first: 'form',
    second: 'form'
  }
};

export const Deck = () => (
  <ViewIdMosaic
    className={'deck'}
    renderTile={(id, path) => (
      <ViewIdMosaicWindow path={path} createNode={() => 'new'} title={id}>
        {id}
      </ViewIdMosaicWindow>
    )}
    initialValue={{
      direction: 'row',
      first: 'datalist',
      second: {
        direction: 'column',
        first: 'form',
        second: 'form'
      }
    }}
  />
);

import * as ReactDOM from 'react-dom';
const root = document.createElement('div');
root.id = 'root';
ReactDOM.render(<Deck />, document.body.appendChild(root));
```

And the stylesheet is pretty simple too:

```
@import '~react-mosaic-component/react-mosaic-component.css';

html, body, #root {
  margin: 0;
  height: 100%;
  width: 100%;
  overflow: hidden;
}

body {
  user-select: none;
  -webkit-user-select: none;
  font-family: 'Fira Sans', Arial, Helvetica, appleLogo, sans-serif;
}
```

We cannot reproduce the problem with the demo application you have in the repository. Are we missing something in the default stylesheet or is this a known bug?

- __Package version(s)__: ^1.0.3
- __Browser and OS versions__: High Sierra, Chrome 63, Firefox 58

Library looks awesome, keep the good work!

**Comment by luisbelloch** [comment]
Ok, I spotted the problem, tile identifiers cannot be duplicated.

```diff
      direction: 'row',
      first: 'datalist',
      second: {
        direction: 'column',
        first: 'form',
-       second: 'form'
+       second: 'any_other_unique_id'
      }
```

Should the library prevent that or at least throw a warning in the console?

**Comment by nomcopter** [comment]
That definitely surprises me - there should be nothing that requires IDs to be unique. Will look in to when I have a chance.

**Comment by nomcopter** [comment]
Oh, nope. The IDs are used as react keys, confusing react with duplicates. I'll add a check - good catch.

**Comment by luisbelloch** [comment]
thanks!  🙂
