### ISSUE TITLE
Add .ofType() method on Mosaic for type-safe consumption

### ISSUE THREAD

**Issue by thelastnode** [palantir/react-mosaic#58]
Right now, TSX does not allow specifying generics. This means any TSX consumer of this component has to use something like this for additional type safety:

```tsx
type MosaicPanelId = "panel-a" | "panel-b" | "panel-c";

const TypedMosaic = (Mosaic as any) as new () => Mosaic<MosaicPanelId>;
```

Ideally, the `Mosaic` component could have a static function for more obvious consumption:

```tsx
const TypedMosaic = Mosaic.ofType<MosaicPanelId>();
```

Prior art: [Blueprint's Select component](https://github.com/palantir/blueprint/blob/3b44d245dec2494a9f14a1ef0544e1a11a7655c0/packages/select/src/components/select/select.tsx#L90-L92)

**Comment by nomcopter** [comment]
That helper definitely sounds useful. Is `new () => Mosaic<MosaicPanelId>` better than `class extends Mosaic<MosaicPanelId> { }`?

From the [README](https://github.com/palantir/react-mosaic/blob/master/README.md#drag-drop--and-other-advanced-functionality-with-mosaicwindow):
```ts
// Make a simple extension class to preserve generic type checking in TSX
class ViewIdMosaic extends Mosaic<ViewId> { }
class ViewIdMosaicWindow extends MosaicWindow<ViewId> { }
```

**Comment by thelastnode** [comment]
`class extends` creates a new class, while `as new () =>` just typecasts the existing class without creating a new one. I don't think the difference is significant, but it might make it easier to read in the React dev tools (where it should show up as `Mosaic` with the cast).
