### ISSUE TITLE
Getting/Setting window sizes programmatically

### ISSUE THREAD

**Issue by partnerinflight** [palantir/react-mosaic#60]
Question: 

If I want to save window state after app close (using this in Electron) and then be able to restore window sizes, how would I go about that? 

Specifically, trying to figure out how to get/set the relative window sizes on initial render. A sample doing this would be very helpful.

Thanks!

**Comment by nomcopter** [comment]
MosaicParent specifies a splitPercentage that you can use to programmatically set the size. I'll leave this issue open to update the docs.

**Comment by nomcopter** [comment]
If you use the react dev tools to inspect the react-mosaic demo you can inspect the state as you drag things around for an example. If you want to get the sizes just use it in a controlled fashion.
