### ISSUE TITLE
MosiacWindow child only updates when window is dragged, not when new props are passed

### ISSUE THREAD

**Issue by merges** [palantir/react-mosaic#65]
Thanks for this great tool. I might be using `MosiacWindow` wrong. (I also use JavaScript only, not TypeScript — yet ;)) In my app, `MosiacWindow` wraps a child chart component that can receive new data as a prop when the user interacts with it. `MosaicWindow`’s `shouldComponentUpdate` function seems to prevent this child from updating when it receives new props (it appears to explicitly block updates based on changes to children). Dragging the `MosaicWindow` allows the update to finally happen.

**SCENARIO**

```
render () {
  // this.state.chartData === { a: [], b: [] };

  const elements = {
    a: <CustomChart data={chartData[a]} onSelectPoints={this.updateChartDataInState} />,
    b: <CustomChart data={chartData[b]} onSelectPoints={this.updateChartDataInState} />
  };

  return (
    <div>
      <Mosaic
        renderTile={(id, path) => <MosaicWindow path={path} title={id}>{elements[id]}</MosaicWindow>}
        initialValue={{
          direction: 'row',
          first: 'a',
          second: 'b',
        }}
      />
    </div>
  );
}
```

I would expect that when I change the child of `MosaicWindow` it would update. When I render the element directly in `renderTile` everything works fine, because there is no `shouldComponentUpdate` stopping the element from updating. Is this expected behavior?

How should I pass new props to a child of `MosaicWindow` and insist that it update?

Thanks!

**Comment by 4ian** [comment]
Indeed, `MosaicWindow` implements `shouldComponentUpdate` a bit like a Pure component: if no props of it are updated, the `MosaicWindow` prevents the update.

> How should I pass new props to a child of MosaicWindow and insist that it update?

To avoid this, you can pass the props that are updating to `MosaicWindow` (even if they are not used directly by MosaicWindow). At least that a solution that worked for me :)
