### ISSUE TITLE
What Does "Make sure react-mosaic-component.css is included on your page."

### ISSUE THREAD

**Issue by JimTheMan** [palantir/react-mosaic#68]
In the README, "2. Make sure react-mosaic-component.css is included on your page."

what is that? please, advice.

**Comment by nomcopter** [comment]
To render properly the styles bundled with `react-mosaic` must be put into your HTML document. This really depends on your build system. How are you styling your page? You should import `node_modules/react-mosaic-component/react-mosaic-component.css` in a similar fashion.

**Comment by dakami** [comment]
import "../node_modules/react-mosaic-component/react-mosaic-component.css";

**Comment by rdunkle-nj** [comment]
Can we update the "Simple Tiling" example in the README to include the `react-moasic-component.css`?

It threw me off reading "Make sure `react-mosaic-component.css` is included in your page", and then the example didn't demonstrate this.

**Comment by nomcopter** [comment]
It really varies based on one's build system - I didn't want to tie the example to webpack.
