### ISSUE TITLE
Passing a custom instance of react-dnd DragDropContext to mosaic component

### ISSUE THREAD

**Issue by alehuo** [palantir/react-mosaic#74]
Hey,

Is there a way to pass a custom DragDropContext to the mosaic component? I am having errors like "Cannot have multiple HTML5 backends" and "Could not find the drag and drop manager in the context of RootDropTargetsClass".

I want to use a custom HTML5 backend because I also have other components that need drag and drop functionality. The HTML5Backend needs to be a singleton instance. Using ```<Mosaic/>``` says I cannot have two HTML5 back-ends at the same time, and using ```<MosaicWithoutDragDropContext/>``` says it can't find the drag drop manager.

App component:
```typescript
import * as PropTypes from "prop-types";
import * as React from "react";
import { DragDropContext } from "react-dnd";
import HTML5Backend from "react-dnd-html5-backend";
import { MosaicWithoutDragDropContext } from "react-mosaic-component";
import "react-mosaic-component/styles/index.less";

const ELEMENT_MAP: { [viewId: string]: JSX.Element } = {
  a: <div>Left Window</div>,
  b: <div>Top Right Window</div>,
  c: <div>Bottom Right Window</div>
};

// context singleton
// tslint:disable-next-line:ban-types
let context: Function;

class App extends React.Component {
  public static childContextTypes = {
    dragDropManager: PropTypes.object.isRequired
  };
  public getChildContext() {
    return {
      dragDropManager: this.context.dragDropManager
    };
  }

  public render() {
    return (
      <div>
        // @ts-ignore
        <MosaicWithoutDragDropContext
          renderTile={id => ELEMENT_MAP[id]}
          initialValue={{
            direction: "row",
            first: "a",
            second: {
              direction: "column",
              first: "b",
              second: "c"
            },
            splitPercentage: 40
          }}
        />
      </div>
    );
  }
}

export default DragDropContext(HTML5Backend)(App);

```

**Comment by nomcopter** [comment]
Hmm, I haven't tried it with the explicit context forwarding before, it _should_ work just as the following:

```tsx
import * as PropTypes from "prop-types";
import * as React from "react";
import { DragDropContext } from "react-dnd";
import HTML5Backend from "react-dnd-html5-backend";
import { MosaicWithoutDragDropContext } from "react-mosaic-component";
import "react-mosaic-component/styles/index.less";

const ELEMENT_MAP: { [viewId: string]: JSX.Element } = {
  a: <div>Left Window</div>,
  b: <div>Top Right Window</div>,
  c: <div>Bottom Right Window</div>
};

class App extends React.Component {
  public render() {
    return (
      <div>
        // @ts-ignore
        <MosaicWithoutDragDropContext
          renderTile={id => ELEMENT_MAP[id]}
          initialValue={{
            direction: "row",
            first: "a",
            second: {
              direction: "column",
              first: "b",
              second: "c"
            },
            splitPercentage: 40
          }}
        />
      </div>
    );
  }
}

export default DragDropContext(HTML5Backend)(App);
```

**Comment by alehuo** [comment]
With that code I also get the same error: ```Could not find the drag and drop manager in the context of RootDropTargetsClass. Make sure to wrap the top-level component of your app with DragDropContext. Read more: http://react-dnd.github.io/react-dnd/docs-troubleshooting.html#could-not-find-the-drag-and-drop-manager-in-the-context```

What could be the cause? For some reason, the ```MosaicWithoutDragDropContext``` doesn't receive the DragDropContext at all.

I wonder if anyone else has the same problem regarding DragDropContext.

**Comment by nomcopter** [comment]
Is this a version compatability issue? Mosaic it's using 2.5.4 of react-dnd. I think it is a few behind current.

**Comment by alehuo** [comment]
Hey, I was using the latest react-dnd. When I switched to version 2.5.4, the problem is gone. The dependency should be updated though, as it's pretty old already.

Thank you for the help!

**Comment by nomcopter** [comment]
Agreed, tracking here #75. Thanks!
