### ISSUE TITLE
Support onRelease layout change callback

### ISSUE THREAD

**Issue by chultquist** [palantir/react-mosaic#80]
Would it be possible to provide a mode where the onChange callback is only called when the user releases the mouse button? This is particularly useful in controlled mode, where the application is only interested in updating its state for the discrete layout changes made by the user & not for all the continuous, incremental layout changes as the user drags things around within a single mouse button press.

**Comment by chultquist** [comment]
I don't see onRelease in the API documentation for react-mosaic. Is that really available or is that within some sub-component? If this is available then that would work for me (with or without the change suggested by Birkenstab).

> Is this for persistence? Is debouncing `onChange` not enough?

Yes, this is for persisting the changed state into a redux store (and ultimately that gets persisted to disk). Debouncing could help but unless you pick your timer value carefully you'll either still get multiple or delayed updates to the redux store. onRelease() support would be much, much better to capture the change that a single mouse drag action had on the layout.

**Comment by nomcopter** [comment]
Makes sense. Will add when I get a chance over the next few days.
