### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by gj1118** [palantir/react-mosaic#81]
Hi , 
Is there a simple example possibly independent of the source code (I know that there is a demo folder with the source code but that is not independent of the source code ) that I can follow to set it up so that I can use it my project. 

A small simple example would suffice. I can figure out the rest afterwards. 

Any help will be well appreciated. 

Thank you so much for your time and patience.

**Comment by nomcopter** [comment]
I recommend starting with something like this https://github.com/Microsoft/TypeScript-React-Starter/ and then installing `react-mosaic-component`
