### ISSUE TITLE
Requires blueprint?

### ISSUE THREAD

**Issue by adiun** [palantir/react-mosaic#88]
I just pulled 2.0.1 and I see that `MosaicZeroState` and `MosaicWindow` now has a dependency on @blueprintjs/core and @blueprintjs/icons. After I upgrade the version I get an error during build saying that it can't resolve @blueprintjs/icons and @blueprintjs/core. Is that intended? I saw PR #10 which removes the dependency...

### Bug report

- __Package version(s)__: 2.0.1
- __Browser and OS versions__: Windows, Chrome 

#### Steps to reproduce

1. I had version 1.1.1 of `react-mosaic-component` without any blueprintjs deps.
2. Changed `1.1.1` to `2.0.1` in package.json
3. `npm install`
4. `npm run build` which runs webpack

#### Actual behavior
```
ERROR in ./node_modules/react-mosaic-component/lib/MosaicWindow.js
Module not found: Error: Can't resolve '@blueprintjs/core' in '...\node_modules\react-mosaic-component\lib'
 @ ./node_modules/react-mosaic-component/lib/MosaicWindow.js 46:13-41
 @ ./node_modules/react-mosaic-component/lib/index.js

ERROR in ./node_modules/react-mosaic-component/lib/MosaicZeroState.js
Module not found: Error: Can't resolve '@blueprintjs/core' in '...\node_modules\react-mosaic-component\lib'
 @ ./node_modules/react-mosaic-component/lib/MosaicZeroState.js 35:13-41
 @ ./node_modules/react-mosaic-component/lib/index.js
```

#### Expected behavior

No build error, no need to install @blueprintjs/core and @blueprintjs/icons.

**Comment by nomcopter** [comment]
Definitely not intended. Will look into.

**Comment by kmannislands** [comment]
Was also surprised by a similar `Module not found: Error: Can't resolve '@blueprintjs/core'` from webpack on fresh installation.
