### ISSUE TITLE
Requires @blueprintjs/core and react-addons-css-transition-group

### ISSUE THREAD

**Issue by codepunkt** [palantir/react-mosaic#9]
Trying to get a feel for the library by using the first example from the readme:

```jsx
<Mosaic
  renderTile={e => e}
  initialValue={{
    direction: 'row',
    first: <div>Left Window</div>,
    second: {
      direction: 'column',
      first: <div>Top Right Window</div>,
      second: <div>Bottom Right Window</div>,
    },
  }}
/>
```

Both packages seem required and should be added as `peerDependencies` as well as to the installation part of the `README.md`.

**Comment by nomcopter** [comment]
Good catch. Looks like the `@blueprintjs/core` dependency snuck in into `MosaicZeroState` and I believe that is where the `peerDependency` for `react-addons-css-transition-group` is coming from as well. 
I'll remove the dependency from `MosaicZeroState` which will fix this.
