### ISSUE TITLE
Accessing MosaicWindowContext via Hooks API

### ISSUE THREAD

**Issue by slnovak** [palantir/react-mosaic#95]
Hello!

First off, thanks for maintaining react-mosaic -- managing a UI layout via a binary tree updated by immutable operations is really clever!

I'm excited to use react-mosaic for a React app that uses the new-and-shiny Hooks API. In my app, I'd like to create windows dynamically. The [Advanced API](https://github.com/palantir/react-mosaic#advanced-api) section in the guide state shows how a component can set `static contextTypes = MosaicWindowContext;` to access the correct context to split windows, however I believe this is using the [legacy Context API](https://reactjs.org/docs/legacy-context.html) to access context.

Do you have any suggestions how one can access legacy Contexts via the Hooks API?

Thanks!

**Comment by nomcopter** [comment]
Hi @slnovak, the new context api should definitely be added to Mosaic. In the meantime you can use a class style component above your Hooks component to grab the legacy context and convert it into the new context.
