### ISSUE TITLE
Import statement references relative path outside this module

### ISSUE THREAD

**Issue by spacedentist** [palantir/react-mosaic#97]
### Bug report

- __Package version(s)__: 2.0.2
- __Browser and OS versions__: webpack 4.2.26

#### Quick fix

Change line 17 in react-mosaic/styles/blueprint-theme.less from

```
@import (reference) '../node_modules/@blueprintjs/core/lib/less/variables';
```

to

```
@import (reference) '~@blueprintjs/core/lib/less/variables';
```

e.g. using

```
sed --in-place 's|../node_modules/|~|g;' react-mosaic-component/styles/blueprint-theme.less
```

#### Steps to reproduce

1. Build a Javascript React app doing
  `import 'react-mosaic-component/styles/index.less';`
2. Build with Webpack, using style-loader, css-loader, less-loader for less files.

#### Actual behavior

```
ERROR in ./node_modules/react-mosaic-component/styles/index.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./node_modules/react-mosaic-component/styles/index.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):


 */
@import (reference) '../node_modules/@blueprintjs/core/lib/less/variables';
^
Can't resolve '../node_modules/@blueprintjs/core/lib/less/variables.less' in '/tmp/js/node_modules/react-mosaic-component/styles'
      in /tmp/js/node_modules/react-mosaic-component/styles/blueprint-theme.less (line 17, column 0)
 @ ./node_modules/react-mosaic-component/styles/index.less 2:14-98
```

#### Expected behavior

Build should pass without error.

**Comment by nomcopter** [comment]
Importing the `react-mosaic-component/styles/index.less` is not supported, please import `react-mosaic-component/react-mosaic-component.css`
