### ISSUE TITLE
Feature request: Ability to provide a custom toolbar implementation

### ISSUE THREAD

**Issue by mejackreed** [palantir/react-mosaic#98]
Thanks for the effort on react-mosaic!

We are currently using it, and would like to be able to provide a custom toolbar implementation that gets wrapped into the `connectDragSource` without having to write our own implementation of `MosaicWindow`. 

Is this something possible with current API?

Are you open to a PR that implements this behavior if not?

Thanks!

**Comment by nomcopter** [comment]
Swapping out the entire toolbar is not currently possible, but a PR to make that possible sounds great!
